- image.ks
This makes it easier for other tools (e.g. the oemid injection script)
to discover the partitions without hardcoding the layout.
Prep for dropping LVM.
> image: Use labels `root` and `boot`

- image.ks
This is transparently used by overlayfs for copyups, rpm-ostree
can use it for the rpmdb, and ostree uses it for `/etc`.
It's The Future.  (Also probably the default for `mkfs.xfs` at
some point I imagine...if that happens we'll need to explicitly
turn it off for `/boot` or perhaps suck it up and use `ext4`
or something)
https://lwn.net/Articles/659677/
https://lwn.net/Articles/747633/
> image: Use reflinks for / by default

- fedora-coreos-base.yaml
Newer versions of serde that we may use for rpm-ostree are more
strict about this.
> base: Ensure version numbers are strings

- fedora-coreos-base.yaml
This drops a file in `/etc/profile.d` which configures the default
value of `PATH` for FCOS. This is mostly only useful for testing
purposes.
> image: install default PATH file

- fedora-coreos.yaml
This reverts commit ee5b62592364fba29926d9fcc70cbda2bc14f823.
Sorry, I'd only done basic testing on this; coreos-assembler doesn't support this yet.
> Revert "manifest: Use ${basearch}"

- fedora-coreos-base.yaml
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/64
> base: add moby-engine

- fedora-coreos.yaml
Like we do elsewhere.  It turns out multiple architectures may be
important...
Depends https://github.com/coreos/coreos-assembler/pull/192
> manifest: Use ${basearch}

- fedora-coreos-base.yaml
This package is only for x86_64 (also i686 if this architecture is
ever suported in the future) which causes non-x86_64 architectures
to fail the rpm-ostree compose.
> manifest: Remove biosdevname from package list

- fedora-coreos-base.yaml
- image.ks
I'd like to change coreos-assembler to have `/var` completely
empty in the disk image, and hence all content is created consistently
via systemd-tmpfiles at boot.
This is an important preparatory step for moving away from Anaconda.
For backwards compatibility (for now) let's auto-create the `core`
user still, but via a systemd unit on boot.  The right thing
I think is to move this logic into Ignition, but this works
for now.
We need to create a `dummy` user in Anaconda since it insists
there's either a root account or a user, but it gets deleted in
`%post`.
> Add coreos-useradd-core.service to create `core` user

- fedora.repo
baseurl differs for primary and secondary arches
in Fedora
> Use metalink instead of baseurl in fedora repo

- fedora-coreos-base.yaml
- image.ks
to make things more distribution neutral
Depends on: https://github.com/coreos/ignition-dracut/pull/30
> ks: Rename $coreos_firstboot grub var to $ignition_firstboot

- fedora-coreos-base.yaml
- rfairley-console-login-helper-messages.repo
Adds the rfairley-console-login-helper-messages COPR repo to download
the console-login-helper-messages package from.
---
Right now, this gets the console-login-helper-messages package and the required PAM version (`pam-1.3.1-12.fc29`) into the build when using coreos-assembler with the config on this branch. These two packages are sourced from COPR https://copr.fedorainfracloud.org/coprs/rfairley/console-login-helper-messages/monitor/.
There are 3 issues left to get motdgen fully working:
1) The main issue left to sort out is making sure the `motdgen` and `issuegen` units are enabled and started without needing to enter the commands manually. As of now, to use them requires the following when first booting in after `coreos-assembler run`:
```
```
2) The other blocker is getting …
> fedora-coreos-base: Add console-login-helper-messages package

- fedora-coreos-base.yaml
Further testing reveals that, for F28/F29 at least, the mptspi
and VMWare PV SCSI driver are already included by dracut when
you specify --no-hostonly.  Removing them here as they are not
actually needed.
> manifest: Remove redundant module includes

- fedora-coreos-base.yaml
This came up in `#silverblue` discussion; let's do it here
first under the general concept that most changes to the "core"
underlying both Silverblue and FCOS should be made in FCOS first.
Tested locally with a build+run.  It doesn't affect the `core`
user today, because anaconda+libuser aren't reading the defaults
from the target OS.
> base: Use /var/home for home directories by default

- fedora-coreos-base.yaml
This adds utils and service units for loading static firewalling rules,
supporting both iptables and nftables flavors.
Ref: https://github.com/coreos/fedora-coreos-tracker/pull/103
> fcos-base: add utils for static firewalling

- fedora-coreos-base.yaml
This should help build a smaller initramfs and clean up the logs a bit
Still testing, will make non-draft once tested
> dracut: omit modules we don't use

- installer/EFI/fedora/grub.cfg
From some brief testing it looks like `linux` and `initrd` work
on x86_64 EFI boot so we'll just use that so we can use the same
grub.cfg for aarch64 or for x86_64.
Fixes #63
> installer: make grub.cfg usable on aarch64

- fedora-coreos-base.yaml
In [1] ignition-dracut was folded into the ignition top level package
so we don't need to include it in the manifest any longer.
[1] https://src.fedoraproject.org/rpms/ignition/pull-request/26
> manifest: drop ignition-dracut

- fedora-coreos-base.yaml
The missing space here broke the service.  We weren't noticing
this because we worked around it in both `cosa run` and kola.
> Fix coreos-useradd-core.service

- fedora-coreos-base.yaml
Ignition 2 and Afterburn no longer sync their authorized_keys.d fragment files to `~/.ssh/authorized_keys`.  Eventually we should have an `AuthorizedKeysCommand` that walks `authorized_keys.d`, but meanwhile we'd like the tools to still work.
https://github.com/coreos/fedora-coreos-tracker/issues/139
> manifest: Read Ignition/Afterburn authorized_keys.d fragments

- fedora-coreos-base.yaml
- image.yaml
This should really be done in rpm-ostree if `machineid-compat: false`
but for now let's do the quick hack here.
The core problem is today the RPM scriptlets are enabling units,
but for us Ignition+presets should be the canonical definition of
things.
This avoids having another source of truth.
> postprocess: Nuke everything in /etc/systemd/system

- fedora-coreos-base.yaml
- overlay/usr/lib/systemd/system-preset/42-coreos.preset
These changes should be added once the update to the latest source lands in stable https://bodhi.fedoraproject.org/updates/console-login-helper-messages-0.16-2.fc29. This update will remove the `.path` units from the source.
This PR can be merged anytime before the update lands as well, as the `.path` units are not involved in the MOTD or issue generation today, and they do not need enabling.
Also lists only the following in the manifest:
```
console-login-helper-messages-issuegen
console-login-helper-messages-motdgen
console-login-helper-messages-profile
```
as the `console-login-helper-messages` package on its own provides common dependencies for the 3 subpackages, and need not be requested explicitly.
> Update console-login-helper-messages manifest and enabled presets

- minimal.yaml
aarch64 is currently using UEFI and not u-boot, additionally the
bcm283x-firmware package is only needed for Raspberry Pi devices which
have the Broadcom BCM283x devices, and can also be safely removed.
> aarch64: Remove unnecessary packages for aarch64

- fedora-coreos-base.yaml
- fedora-coreos-continuous.repo
We have f*-coreos-continuous reps in place which we can
use to include packages not yet available in Fedora stable
or updates repos.
Related - https://pagure.io/releng/issue/8165
Signed-off-by: Sinny Kumari <sinny@redhat.com>
> Use fedora-coreos-continuous repo for custom builds

- fedora-coreos-base.yaml
This doesn't remove all things with python dependencies, just authconfig
and nfs-utils (replaced by nfs-utils-coreos).
Tested, works.
Addresses https://github.com/coreos/fedora-coreos-tracker/issues/123 and https://github.com/coreos/fedora-coreos-tracker/issues/121
> fedora-coreos-base: rm things with python deps

- fedora-coreos-base.yaml
Remove these as they depend on python
closes https://github.com/coreos/fedora-coreos-tracker/issues/122
closes https://github.com/coreos/fedora-coreos-tracker/issues/126
> base: rm setools-console, policycoreutils-python

- fedora-coreos-base.yaml
- overlay/usr/lib/systemd/system-preset/42-coreos.preset
Add Afterburn to the package manifest, and enable the provider checkin
services through the coreos preset file.
Part of coreos/fedora-coreos-tracker#4.
---
Now gets sourced from `fedora-coreos-pool`:
```
afterburn-4.1.0-1.module_f30+4209+68fe9bdd.x86_64 (fedora-coreos-pool)
```
> Add afterburn package

- image.yaml
Requires https://github.com/coreos/coreos-assembler/pull/525.  Implements https://github.com/coreos/fedora-coreos-tracker/issues/181.
> Have the kernel conditionally disable SMT if vulnerable

- fedora-coreos-base.yaml
For https://github.com/coreos/fedora-coreos-tracker/issues/138.  We don't support `sshd_config` fragments yet, so the only way to override this with Ignition is by writing a `ConditionFirstBoot=true` unit `Before=sshd.service` that runs `sed` over `sshd_config`.  But it is _possible_ to override it, so let's start testing with this configuration.
> Disable SSH password logins by default

- overlay/usr/lib/dracut/modules.d/40coreos-network/coreos-teardown-initramfs-network.service
- overlay/usr/lib/dracut/modules.d/40coreos-network/coreos-teardown-initramfs-network.sh
- overlay/usr/lib/dracut/modules.d/40coreos-network/module-setup.sh
Add coreos-teardown-initramfs-network.service to run after ignition
has finished using initramfs networking, so NetworkManager properly
brings up ignition-configured networking in the real root. Otherwise
the initramfs network persists into the real root.
Note: I'm not sure what the correct priority is, so I made it 40 to match other services.
It shouldn't really matter since this service actually runs during `ExecStop` and
before `Before=initrd-switch-root.target`.
> overlay: add 40coreos-network dracut module

- overlay/usr/lib/systemd/system-preset/42-coreos.preset
With https://github.com/coreos/afterburn/pull/217 in Fedora, enable
this unit in FCOS.
---
Hold until the updated module (https://release-engineering.github.io/mbs-ui/module/4325) is finished building and tagged in `coreos-pool`.
> overlay: Enable afterburn-sshkeys@.service

- fedora-coreos-base.yaml
Pursuant to coreos/fedora-coreos-tracker#186.  Subsumes, I think, the relevant part of https://github.com/coreos/fedora-coreos-config/pull/54.
> Remove some stuff from the image
